# -*- coding: utf-8 -*-
"""iot_simulator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aUvTo2LyyRVhguFaVerPnSccFuVYKjgP
"""

import numpy as np
import pandas as pd

# Set a seed for reproducible results
np.random.seed(42)

# Generate normal data: 1000 readings for 2 sensors (Temperature, Humidity)
normal_temperature = np.random.normal(25, 2, 1000)  # Mean=25, Std=2
normal_humidity = np.random.normal(50, 5, 1000)     # Mean=50, Std=5

# Create a DataFrame (like a spreadsheet table)
normal_data = pd.DataFrame({
    'Temperature': normal_temperature,
    'Humidity': normal_humidity
})

# Now create some anomalous data (e.g., a sensor fault or attack)
anomalous_temperature = np.random.normal(60, 2, 50) # Mean=60 (very hot!)
anomalous_humidity = np.random.normal(50, 5, 50)    # Normal humidity
anomalous_data = pd.DataFrame({
    'Temperature': anomalous_temperature,
    'Humidity': anomalous_humidity
})

# Combine the normal and anomalous data
full_data = pd.concat([normal_data, anomalous_data], ignore_index=True)

# Save to local Colab storage
full_data.to_csv('/content/iot_data_stream.csv', index=False)
print("IoT data stream saved locally")

# Download to your computer (optional)
from google.colab import files
files.download('iot_data_stream.csv')